services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: lucky.ecommerce:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__NortwindConnection=Server=localhost,1433;Database=Northwind;User Id=sa;Password=C3nt3n4r102024;
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-2022-dev
    environment:
      SA_PASSWORD: "C3nt3n4r102024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet

volumes:
  sql_data:
        driver: local

networks:
  appnet:
    driver: bridge
