name: Deploy to Render 

on:
  push:
    branches:
      # - main
      - feature/postgresql-integration  # Aquí puedes poner las ramas que quieras que disparen el deploy
  workflow_dispatch:  # Para poder lanzarlo manualmente desde GitHub Actions UI 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Usa la misma versión que tienes en tu Dockerfile

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the app
        run: dotnet build Lucky.Ecommerce.sln --configuration Release --no-restore

      - name: Test the app
        run: dotnet test Lucky.Ecommerce.sln --no-build --verbosity normal

      - name: Deploy to Render using API REST
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}'
